// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsJLp1priTkjDzELSMcYrzrofnYZfm5Pg',
    appId: '1:99476230533:web:799827c247b6beefbd34ec',
    messagingSenderId: '99476230533',
    projectId: 'caleb-cj-williams-cb8c7',
    authDomain: 'caleb-cj-williams-cb8c7.firebaseapp.com',
    storageBucket: 'caleb-cj-williams-cb8c7.firebasestorage.app',
    measurementId: 'G-PT4V651QHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPcRAPLr2HBv7slhHdiL3_-spSjDnjXn4',
    appId: '1:99476230533:android:cda5d0e32e956ba6bd34ec',
    messagingSenderId: '99476230533',
    projectId: 'caleb-cj-williams-cb8c7',
    storageBucket: 'caleb-cj-williams-cb8c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8120ckE1I7qR6_JKjPpfQYo4Hyqj9lf0',
    appId: '1:99476230533:ios:787dbd6bc0520da0bd34ec',
    messagingSenderId: '99476230533',
    projectId: 'caleb-cj-williams-cb8c7',
    storageBucket: 'caleb-cj-williams-cb8c7.firebasestorage.app',
    iosBundleId: 'app.ios.caleb-cj-williams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8120ckE1I7qR6_JKjPpfQYo4Hyqj9lf0',
    appId: '1:99476230533:ios:787dbd6bc0520da0bd34ec',
    messagingSenderId: '99476230533',
    projectId: 'caleb-cj-williams-cb8c7',
    storageBucket: 'caleb-cj-williams-cb8c7.firebasestorage.app',
    iosBundleId: 'app.ios.caleb-cj-williams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsJLp1priTkjDzELSMcYrzrofnYZfm5Pg',
    appId: '1:99476230533:web:799827c247b6beefbd34ec',
    messagingSenderId: '99476230533',
    projectId: 'caleb-cj-williams-cb8c7',
    authDomain: 'caleb-cj-williams-cb8c7.firebaseapp.com',
    storageBucket: 'caleb-cj-williams-cb8c7.firebasestorage.app',
    measurementId: 'G-PT4V651QHM',
  );
}